- seriallist_darwin.go
- seriallist_linux.go
Reverts arduino/arduino-create-agent#9
> Revert "Fix bug about non arduino boards not showing up"

- certificates.go
- main.go
How to test:
$ ./ArduinoCreateBridge -generateCert
will generate some certificates in the folder
$ ./ArduinoCreateBridge
will start the agent.
In the browser you need to import the certificate ```ca.cert.pem```
> Certificates

- main.go
Trying to fix issue #56 during the Torino HackNight contest.
The idea is basically to select a pair of free port from port-range using the `net.Listen` function.
The two ports are later used by gin to listen for incoming HTTP or HTTPS connections.
> Stricter CORS headers

- killbrowser.go
- killbrowser_darwin.go
- killbrowser_linux.go
- killbrowser_windows.go
- main.go
Add a POST endpoint named /killbrowser
Fix issue https://github.com/arduino/webide/issues/853
```
$.post("http://localhost:8991/killbrowser", '{"process": "chrome", "action": "restart", "url": "https://create-dev.arduino.cc"}')
```
> Kill and restart the browser

- bufferflow.go
- bufferflow_timedraw.go
- hub.go
- main.go
- serial.go
- serialport.go
encodes data in base64 so it needs to be decoded on the other side
solves #29
> Add bufferflow timedraw

- config.ini
Scratch hardware extensions are written in JavaScript and loaded in
[Scratch](https://scratch.mit.edu) or the experimental extension site, [ScratchX](http://scratchx.org).
This change will allow the [Scratch Arduino extension](http://khanning.github.io/scratch-arduino-extension/) to use the
Create agent to communicate directly with Arduino boards.
> Add CORS origins for Scratch and ScratchX

- config.ini
Removing the entries for Scratch and ScratchX while we look
into what changes are necessary to make this useful for the
Scratch Arduino extension.
> Remove Scratch and ScratchX CORS entries

- main.go
- trayicon.go
Fix https://github.com/arduino/webide/issues/1072
> Remove staging references

- README.md
- conn.go
- programmer.go
Accepts a json object with the base64 encoded binary as the hex field.
Refer to https://github.com/arduino/webide/pull/1127
> Support safari by changing the upload handler

- conn.go
Previously the command signature was only being verified in network mode, when it needs to be checked in non-network mode instead.
> Only check command signature in non-network mode

- conn.go
- tools/download.go
- tools/hidefile_darwin.go
- tools/hidefile_linux.go
- tools/hidefile_windows.go
To allow upload using tools which rely on {runtime.*} variables
Actions server side:
- Compile a "blacklist" (eg : {runtime.platform.path}/variants/{build.variant} )
- Replace these entries with {build.path} when found in commandline
- Map the blacklisted entry to a set of extra files to be uploaded
- Profit
> Allow attaching additional files in the POST

- hub.go
Basically the latest version of avrdude doesn't work on windows, so we instead download the latest version we know it's working.
This is a temporary fix until we have a better way to handle things.
> Download the latest working version of avrdude instead of the latest

- upload/upload.go
A better way would be to use sync.Map but we need to update go to 1.9 first
> Mitigate race conditions on upload

- tools/download.go
When compiling the agent on 64-bit Windows, tool downloads fail, as no
64-bit Windows builds of the tools are available (as far as I can tell).
This commit directs agents compiled for 64-bit Windows to just download
the 32-bit Windows variant of the tool.
Please note that while I have confirmed that this fix works for me (by successfully downloading bossac and uploading a program to my Arduino Due), I'm not sure if there are any side-effects of this change that I'm not aware of. Please let me know if there's anything wrong with this pull request.
Close #199.
> Fix tool download on 64-bit Windows

- upload/upload.go
To upload to a mkr1000 via wifi you actually have to send a command to arduinoOta, so it's basically a serial upload. But you need to specify the password of the board, so here's this commit that lets you do it
Signed-off-by: Matteo Suppo <matteo.suppo@gmail.com>
> Replace info in commandline about password

- info.go
Exposing config.ini properties to let frontend perform configuration checks
> expose origin end update flags when calling /info

- conn.go
- tools/download.go
- tools/download_test.go
- upload/upload.go
Ensures that the parent folder of a file exists even if the tar.gz doesn't explicitely specify the header for that folder.
> Create parent folder for files in archives

- main.go
The trayicon is displayed as soon as possible, in a goroutine.
A select is used to block forever (before it was the trayicon that did
it)
> Prevent delays from displaying the trayicon

- main.go
When an old version autoupdates, it often sends -gc and -regex as
commandline, while they should be parsed from the ini file.
This way the autoupdate will still work. In a later release we'll
remove them.
> Add ignored flags for compatibility

- tools/download.go
The extraction of some tools failed because the parent folder of
some files wasn't created with useful permissions.
Here we correctly set the permission such as the folder has
exec and write permission for the current user
A more long-term solution would be to offload these extractions to a dedicated library, but first we need to merge #254 and to do that jenkins must be configured to use go 1.10
> Set correct permissions when downloading tool [WE-44]

- README.md
- tools/download.go
fixes #260 
- Adds map entry to support arm tooling
- add go version info in readme under "development" section
Tested on a raspberry pi 3 model B v1.2 and an Arduino Mega
> [WE-158] Linux arm tool fix

- info.go
Example of data:
```
{
...
"os": "linux:amd64",
...
}
```
This can be useful for system-based decisions, such as installing windows-specific drivers
> Return info about the system

- upload/upload.go
This PR fixes a path generation in upload command in windows environment:
Error has this form for Arduino WiFi Rev2:
`Flashing with command:C:/Users/per/.arduino-create/arduino/avrdude/6.3.0-arduino14/bin/avrdude.exe -CC:/Users/per/.arduino-create/arduino/avrdude/6.3.0-arduino14/etc/avrdude.conf -v -patmega4809 -cxplainedmini_updi -Pusb -b115200 -e -D -Uflash:w:C:/Users/per/AppData/Local/Temp/arduino-create-agent248491772/sketch_feb28a.hex:i -Ufuses:w:C:UsersperAppDataLocalTempextrafiles293253675/fuses/fuses_4809.bin:r`
`-Ufuses:w:C:UsersperAppDataLocalTempextrafiles293253675/fuses/fuses_4809.bin:r`
should be
`-Ufuses:w:C:/Users/per/AppData/Local/Temp/extrafiles293253675/fuses/fuses_4809.bin:r`
this has properly tested on all 3 platforms
> [WE-205] sanitize paths when replacing {runtime.platform.path}

- v2/pkgs/indexes.go
- v2/pkgs/indexes_test.go
- v2/pkgs/tools.go
- v2/pkgs/tools_test.go
When you attempt to download the same tool twice it can fail
if there are symlinks inside the archive. By removing the folder
we make sure we start from scratch every time
Also indexes were behaving badly attempting to parse extraneous files
> Fix duplicate tool bug

- v2/pkgs/indexes.go
- v2/pkgs/tools.go
see for reference http://forum.arduino.cc/index.php?topic=610882
This PR was made on a windows system to be sure that the fix is real:
- replace PathEscaping with encoding in base64 for downloaded index filenames in order to be compatible on windows FS
- add tool entry with version in installed.json
- fix extracting renaming using standard path
this has to be retested on all OSes
> Fix windows v2 download tool [EDITOR-140]

- serialport.go
buffered_ch was being rewritten with data being read on a later Read()
Attention: this implementation "leaks" (ch will be garbage collected every time)
Please profile the memory usage before merging
> Reinitialize serial buffer on every read to avoid concurrent rewrite

- serialport.go
Reverts arduino/arduino-create-agent#486 due to Create Serial Monitor missing output for high serial write frequency on Arduino Uno
> Revert "Port fix: Reinitialize serial buffer on every read to avoid concurrent rewrite"

- .gitignore
- README.md
- manifest.xml
The embed must be done on jenkins since the rsrc.syso breaks other builds
> Create manifest for windows and add instructions

- .github/workflows/test.yml
CI feature
no artifacts is uploaded by the ci
artifacts of the compiled executables are uploaded
no
> add ci step to upload artifacts

- .github/workflows/test.yml
- Taskfile.yml
- go.mod
- go.sum
Bug fix
the windows executable is not working and it's crashing with `TTM_ADDTOOL failed` error
Now windows executable should work correctly
no
> fix win executable crashing (add manifest to the executable during compile)

- .github/workflows/check-certificates.yml
feature
This workflow checks the expiration date of our Windows and macOS sign certificates and reports their expiring date if needed. Thank you @per1234 
no
> add workflow to check certs expiring date

- .github/workflows/release.yml
feature
add codesign and notarization on macOS
no
> Add codesign and notarization for macOS binary

- .github/workflows/release.yml
just like the arduino-cli does
feature
Add steps to the `release.yml` workflow:
1. to detect if a release is a prerelease or not :question: 
2. to publish release installers to arduino servers automatically (in case of a full release) :arrow_down_small: 
nope
> Publish release on arduino download servers 

- .github/workflows/check-certificates.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
`ubuntu-latest` will be an alias to `ubuntu-20.04` instead of `ubuntu-18.04` https://github.com/actions/virtual-environments/issues/1816
I've pinned github actions virtual environments to an explicit version to not get unexpected behaviours. 
no
> Pin github actions virtual environment versions

- .github/workflows/release.yml
- .github/workflows/test.yml
- Taskfile.yml
CI
Align `test.yml` to `release.yml` and add again upload artifacts: It's really useful to have a reproducible environment to compile the code for every platform.
hardcode gon config for uniformity
Introduce win 64bit build
Change macOS min supported version to 10.11 -> change go version used to build from 1.15 to 10.14 (because of macOS)
Have `test.yml` to push artifact with `0.0.0-dev` in order to block create auto-update  
no
> CI polishing, add win64, update macOS min version 

- .github/workflows/release.yml
- systray/systray_real.go
rename
Sometimes we refer to the agent with the wrong nomenclature (e.g. Pluging or Bridge) 
Rename Plugin or Bridge to Agent
Yes
> Fix naming inconstistencies

- main.go
- systray/systray.go
bug fix
Fixes a regression introduced in #551 (https://github.com/arduino/arduino-create-agent/pull/551/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R139)
When the binary file ending with `-temp` is manually started it does not start the correct bin file but it keeps starting itself. 
Fixed. Now when the temp binary is started it correctly copy itself to the full binary (binary file not ending with `-temp`) and starts it
no
> Fix temp binary not starting correclty

- .github/workflows/release.yml
- .github/workflows/test.yml
- updater/updater.go
feature, CI
auto-update is not enabled
With this PR I will enable auto-update in the CI and I'll make some fixes in the auto-update related code
no
> Enable autoupdate

- .github/workflows/release.yml
- .github/workflows/test.yml
- config.ini
Optimizations before 1.2.0 release
Fixes and improvements before 1.2.0 :tada: 
> Change release filenames and finalize CI

- home.html
- main.go
- Format json output
- Fix elements height to avoid undesired growing of the output box
- Fix checkbox option issue
https://arduino.atlassian.net/browse/EDITOR-559
- Ouput is now a bit more formatted -> easier to read and understand
- Buttons and controls in the bottom part of the page remain visible
- Uncheck "Enable List Command", disables list boards outputs only
no
Please test it 
[EDITOR-559]: https://arduino.atlassian.net/browse/EDITOR-559
> Improvements on the Debug Console 

- docs/tools.md
- tools/download.go
- tools/tools.go
Bug fix
Sometimes the agent randomly crashes with `fatal error: concurrent map read and map write`
The crashreport contains something like:
```
fatal error: concurrent map read and map write
goroutine 2178 [running]:
runtime.throw(0xd4c202, 0x21)
/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/panic.go:1116 +0x72 fp=0xc0007e7680 sp=0xc0007e7650 pc=0x4372f2
runtime.mapaccess2(0xc3f740, 0xc0001106c0, 0xc0004f40a0, 0xc0004f40a0, 0xc000630902)
/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/map.go:469 +0x258 fp=0xc0007e76c0 sp=0xc0007e7680 pc=0x411908
reflect.mapaccess(0xc3f740, 0xc0001106c0, 0xc0004f40a0, 0xd42538) …
```
> [EDITOR-512] Fix concurrent map read and map write

- .github/workflows/release.yml
- .github/workflows/test.yml
- .gitignore
- Taskfile.yml
- poetry.lock
- pyproject.toml
- test/conftest.py
- test/test_certs.py
- test/test_info.py
- test/test_update.py
- test/test_v2.py
add e2e test infrastructure based on arduino-cli's one (using python and pytest)
test infrastructure is added, also to CI
no
> [EDITOR-527] E2E testing infrastructure

- .github/workflows/release.yml
buf fix
[EDITOR-503]
[EDITOR-503]: https://arduino.atlassian.net/browse/EDITOR-503
> [EDITOR-503] fix wrong agent version in spotlight [MacOs]

- .github/workflows/close-stale-issues.yml
CI
Issues older than 14 days (labeled with **waiting for feedback**) will be marked as stale if they are inactive for 14 days and then closed after another 7 days
> [EDITOR-607] add workflow to close stale issues (labeled with waiting for feedback)

- bufferflow_timed.go
- bufferflow_timedraw.go
- serialport.go
feature
Currently we only get a serial object formatted like this `{"D":"output text here\r\n"}`
The output now includes the port generating the output: 
```
{
"P": "dev/ttyACM0",
"D":"output text here\r\n"
}
```
Probably not
> [EDITOR-621] add port to serial output

- go.mod
- go.sum
feature
https://github.com/arduino/arduino-create-agent/issues/611
try to make an experimental build to support for mac m1
> Add serial discovery support for m1 mac

- tools/tools.go
Bug fix, followup of #585 
Sometimes the agent responds with a 500 error to `curl ‘http://127.0.0.1:8991/v2/pkgs/tools/installed’` with this payload `{“name”:“fault”,“id”:“JOhq4y8g”,“message”:“invalid character ‘s’ after top-level value”,“temporary”:false,“timeout”:false,“fault”:true}`.
This error should be caused by a race condition with the result that `installed.json` file gets corrupted
This PR should fix this behavior by adding a stricter mutex policy and releasing the mutex only after the file has been written
no
> use stricter mutex policy to prevent installed.json corruption

- .github/workflows/release.yml
- .github/workflows/test.yml
enhancement
An unmaintained, deprecated, and outdated version of the action used to install Task is in use in the CI/CD workflows.
-  **What is the new behavior?**
The GitHub Actions action for installing [Task](https://taskfile.dev/#/) has graduated from its original home in [the experimental `arduino/action`repository](https://github.com/arduino/actions) with a move to a dedicated permanent repository at [`arduino/setup-task`](https://github.com/arduino/setup-task).
A [1.0.0 release](https://github.com/arduino/setup-task/releases/tag/v1.0.0) has been made and [a `v1` ref](https://github.com/arduino/setup-task/tree/v1) that will …
> Use new arduino/setup-task action name in CI/CD workflows

- .github/workflows/release.yml
fix bug introduced in #639
Bug fix
The workflow is not working correctly
Nop
> [skip-changelog] fix create-changelog action failing because it could not find a git repo

- .github/workflows/check-certificates.yml
Infrastructure update
We have assembled a collection of reusable GitHub Actions workflows:
https://github.com/arduino/tooling-project-assets
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" workflow, but those have not yet been pulled into this repository.
Workflow is synced with the state of the art from upstream.
Not breaking
> Sync "Check Certificates" GitHub Actions workflow with template

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
Infrastructure fix
The **Test Go** workflow on Windows is broken after the newest release of Task (3.9.1) and was working fine with 3.9.0
The problem should be linked to the upgrade in `mvdan/sh` they did in 3.9.1.
The bug is present only on Windows, apparently the PATH env variable is not expanded correctly under subcommands.
To mitigate the issue, we decided to pin the task version used to 3.9.0 in the workflows
no
> Pin task version to 3.9.0 because of the PATH on win bug

- .github/workflows/close-stale-issues.yml
Infrastructure update
The [Close Stale Issue](https://github.com/arduino/arduino-create-agent/actions/workflows/close-stale-issues.yml) is failing to a misconfiguration
I took the opportunity and added `workflow_dispatch` trigger and bumped the action to the latest version, supersedes #652 
> [skip-changelog] fix and update Close stale issue workflow

- .github/workflows/close-stale-issues.yml
The previous incorrect key name `permission` caused the workflow run to error:
https://github.com/per1234/arduino-create-agent/actions/runs/1525440740
```
Invalid workflow file : .github/workflows/close-stale-issues.yml#L7
The workflow is not valid. .github/workflows/close-stale-issues.yml (Line: 7, Col: 1): Unexpected value 'permission'
```
The correct key name is `permissions`:
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
> Correct key name in "Close stale issues" workflow

- .github/workflows/release.yml
bump installbuilder container to the latest available version (21.9.0) https://installbuilder.com/changelog.html
This version should solve some bugs on osx
no
> bump installbuilder container to the latest version

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
This reverts commit 320f7de334005f309fd8487ec3b3c11d235ba191.
infrastructure update
https://github.com/arduino/tooling-project-assets/pull/186
nop
> [skip-changelog] Revert "Pin task version in workflows running on windows (#677)"

- serial.go
- seriallist.go
buf fix (closes #667)
see #667 
no
> fix the listing of the boards

- serial.go
bug fix
The release workflow was failing when running `go vet` with:
```
./serial.go:117:32: call of json.MarshalIndent copies lock value: github.com/arduino/arduino-create-agent.SpPortList contains sync.Mutex
./serial.go:121:32: call of json.MarshalIndent copies lock value: github.com/arduino/arduino-create-agent.SpPortList contains sync.Mutex
```
fixed
nop
> fix `go vet` failing, followup of #668

- poetry.lock
- pyproject.toml
fix tests
The tests are failing
The test are working:
- https://github.com/python-poetry/poetry/discussions/4830
- https://github.com/pytest-dev/pytest/issues/8539
The problem was originating from a newer version of python already including `pathlib`
nop
> fix tests failing

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
see https://github.com/actions/virtual-environments/issues/5583
- N/A Tests for the changes have been added (for bug fixes / features)
infrastructure bump
https://github.com/arduino/arduino-create-agent/runs/7540773194?check_suite_focus=true
bump the runner to `macos-11`
nope
> github runner `macos-10.15` is deprecated, bump to `macos-11`

- .github/workflows/check-certificates.yml
- .github/workflows/check-go-dependencies-task.yml
- .github/workflows/check-license.yml
- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- .github/workflows/sync-labels.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
~~- [ ] Tests for the changes have been added (for bug fixes / features)~~
CI fix
The bundles generated by the CI are not valid on macOS Ventura
The bundles are valid:
- the notarization happens only for the binary and not for the bundle
- bumped the runners
- fixed the usage of `set-output commands`
- general enhancements
-----
nope
> The CI is now able to produce valid macOS Ventura bundles

- Taskfile.yml
enhancement
Few enhancements in the taskfile to make it more contributor friendly and align it to the asset repo
The taskfile is :sparkles: 
no
> Enhance the taskfile

- .licenses/arduino-create-agent/go/github.com/xrash/smetrics.dep.yml
- go.mod
- go.sum
- tools/download.go
- tools/download_test.go
- tools/testdata/test_tool_index.json
Fix #751 
See #751 
The agent should be able to select the correct tool system to download
no
> Fix amd64 darwin install wrong tool (amd64)

- .github/workflows/release.yml
CI enhancement
The autoupdate bundle is not pushed to s3 download servers
During a release, a notarized zipped bundle is produced and pushed directly to s3 download server, inside a directory that includes the version tag.
no
Close #736
> Upload the signed bundle to s3

- .github/workflows/release.yml
~~- [ ] Tests for the changes have been added (for bug fixes / features)~~
CI enhancement, companion of #756
Close #757 
The CI uploads 2 json files to s3 download bucket containing the version and the checksum of the zipped bundle.
no
> add json to enable autoupdate with the new agent logic

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- .licenses/arduino-create-agent/go/github.com/arduino/go-paths-helper.dep.yml
- config.go
- main.go
- systray/systray_real.go
The `config.ini` is no more part of the Arduno Create Agent package resources, but it is generated and saved in a user's home subfolder.
In theory no. An old customized `config.ini` should be detected and moved to the new correct location.
> Rework `config.ini` path handling

- main.go
- systray/systray.go
- systray/systray_real.go
Adds the "Open Config..." menu item, to open the current configuration file.
"Open Config file" menu is missing.
Fix #734
> Add "Open config file" menu item

- README.md
Run a linter pass on README.md
> Linted README.md

- main.go
- update.go
- updater/updater.go
- updater/updater_darwin.go
- updater/updater_default.go
- updater/updater_macos.go
This PR refactor the `updater` package, it aims to provide a more defined API for the autoupdate feature.
The API defined here is composed of two function that the auto-updater should implement:
```go
// Start checks if an update has been downloaded and if so returns the path to the
// binary to be executed to perform the update. If no update has been downloaded
// it returns an empty string.
func Start(src string) string {
return start(src)
}
// CheckForUpdates checks if there is a new version of the binary available and
// if so downloads it.
func CheckForUpdates(currentVersion string, updateAPIURL, updateBinURL string, cmdName string) (string, error) {
return …
```
> Refactor updater API

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- go.mod
- systray/exec_darwin.go
- systray/exec_default.go
- systray/systray.go
- update.go
- updater/updater.go
- updater/updater_darwin.go
- updater/updater_default.go
Implements a new auto-update procedure to handle the new security features of MacOS Ventura.
The old auto-update replaces the Agent executable binary in place, this method does not work anymore because it breaks MacOS Ventura checks for the application's signature.
The new auto-update method replaces the whole `.app` folder.
It also uses the MacOS Cocoa SDK function `openApplicationAtURL:url` to restart the app after the upgrade.
No
> Fix macosx ventura updater

- config/autostart.go
fix corner case introduced in #781 
Fix #788, the agent is now able to detect if the autostart file needs to be overwritten or not
The agent is now able to update the autostart file when it's required.
no
> Update the autostart file when it's required

- .github/workflows/release.yml
- main.go
- updater/updater_darwin.go
bug fix
when uninstalling an old version of the agent (e.g. 1.2.7) a folder in `~/Applications/ArduinoCreateAgent` could be left behind (empty, but existing), after uninstalling.
This will trigger this error when running a new agent:
The check in the new agent is performed on the existence of the `ArduinoCreateAgent.app` subfolder.
no
Partially fixes #795
> Check the folder content in new version of the agent on macos

- hub.go
- systray/systray_real.go
bug fix
When the frontend connects to the agent a command is sent to download the required tools (for flashing/fwupload etc...). This command `downloadtool` had a strange behavior: It used to remove the certificates in the user dir.
This has been removed since it's no longer necessary
no
> Fix https certificates being removed after `downloadtool` command

- config/autostart.go
- It didn't look like there were any tests for the config module—if I missed it, though, let me know! (Adding a whole test file for `config` at this time felt a bit out of scope imo) Happy to add them in another place though!
In the meantime, here's a quick Gist you can run to test out the changes locally: https://gist.github.com/xplato/ff85973647e9a1b5190361e331c27fe0
This is a bug fix in the `config` module. On MacOS, sometimes the `~/Library/LaunchAgents/` directory does not exist—if not, this would cause the program to not start because the path to the config file would be invalid (see the end of this PR description for the relevant log/info). This will create the directory if it doesn't exist, allowing the program to run correctly.
- …
> Create `LaunchAgents/` directory if it doesn't exist (MacOS)

- conn.go
- tools/download.go
- tools/download_test.go
- tools/tools.go
- upload/upload.go
- utilities/utilities.go
- v2/pkgs/indexes.go
- v2/pkgs/indexes_test.go
- v2/pkgs/tools.go
- v2/pkgs/tools_test.go
remove [deprecated package](https://pkg.go.dev/io/ioutil)
Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
We use package io or os
no
> Remove io/ioutil since is deprecated

- tools/download.go
- tools/download_test.go
- tools/testdata/test_tool_index.json
- v2/pkgs/pkgs.go
- v2/pkgs/tools.go
Bug fix
Tools for Windows 32-bit are downloaded when the OS/Arch is Windows 64-bit.
The correct tools are downloaded for Windows 64-bit.
No
> Download the correct tools for Windows 64-bit

- .github/workflows/check-go-dependencies-task.yml
- .github/workflows/check-go-task.yml
- .github/workflows/check-license.yml
- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- .github/workflows/sync-labels.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
> Bump actions/checkout to v4

- .licenses/arduino-create-agent/go/go.bug.st/serial.dep.yml
- .licenses/arduino-create-agent/go/go.bug.st/serial/enumerator.dep.yml
- .licenses/arduino-create-agent/go/go.bug.st/serial/unixutils.dep.yml
- discovery.go
- go.mod
- go.sum
- main.go
- serial.go
- seriallist.go
- serialport.go
* Fixes the behavior of failing enumerators.
* Fixes the underlying bug for #808 
If an en enumerator starts failing the current port list is retained. This leads to strange behaviors like #808.
The new behavior is to clean up the port list if the enumerator fails to enumerate the ports.
No
This PR contains two fixes:
* a workaround for #808
* an actual fix for the main problem: the enumerator produces the following error with some peculiar hardware setups:
```
Error while enumerating serial ports: IOServiceGetMatchingServices failed, data changed while iterating
```
The fix is here: https://github.com/bugst/go-serial/pull/165
and
* I've also added some refactorings that are not strictly related to this issue but …
> bugfix: serial enumerator failures in some rare circumstances

- conn.go
- main_test.go
- utilities/utilities.go
- utilities/utilities_test.go
- v2/pkgs/tools.go
- v2/pkgs/tools_test.go
Fixes: https://arduino.atlassian.net/browse/PNX-1543
Fixes: https://arduino.atlassian.net/browse/PNX-4130 (e52373197eee9e5f8b08ebe91bd339dcfc6d3d36)
> Use SafeJoin in the uploadHandler

- certificates/install_darwin.go
- systray/exec_darwin.go
> fix memory leak

- .github/workflows/release.yml
bugfix :lady_beetle: 
The agent builds after 1.2.7 on linux have different kind of problems:
1. `1.3.0`, `1.3.1`, `1.3.2` are being built for linux 32 bit (see #803)
2. `1.3.3` does not contain the agent binaries (see #846)
I thought to have fixed #803, in the installer repo, but the regression comes from [this change](https://github.com/arduino/arduino-create-agent/commit/b62a2ff745c804f12ea1dcb6d8856602d5aa8545#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R426) (note the argument to `installbuilder` has been changed from `linux-x64` to `linux`).
This PR will
1. fix #803 …
> fix agent being built for 32 bit linux for real

- .github/workflows/release.yml
change in tooling see https://github.com/arduino/tooling-project-assets/issues/359
An excellent tool named [gon](https://github.com/mitchellh/gon) was used to perform the notarization.
the latest stable release of gon uses the altool command-line utility for notarization:
https://github.com/mitchellh/gon/blob/v0.2.5/notarize/upload.go#L41
Using altool for notarization is now deprecated by Apple and support for notarization via this tool is scheduled to be disabled 2023-11-01:
https://developer.apple.com/news/?id=y5mjxqmn
Furthermore, gon was archived
I switched to https://github.com/Bearer/gon that …
> Replace mitchellh/go used for macOS notarization

- .github/workflows/release.yml
Installer Bug fix
Fix #854 
The condition was wrong: we were only using the else branch. This was causing the linux installers to not contain the actual binary. We do not support running installbuilder with `linux` as a target, we support `linux-x64`
The installbuider linux installers are generated the right way.
No
> Fix installbuilder not able to produce complete artifacts for linux

- main.go
- [N/A] Tests for the changes have been added (for bug fixes / features)
Bug fix
If the `v` key is not set to `true` in the configuration file, Arduino Create Agent prints a seemingly helpful message to the terminal:
```text
You can enter verbose mode to see all logging by starting with the -v command line switch.
```
However, it is not helpful after all because there is no `-v` command line flag. The sole mechanism for controlling logging is the `v` key of [the configuration file](https://github.com/arduino/arduino-create-agent/wiki/Advanced-usage#the-configuration-file-location). If the user follows the instructions they will get an error:
```text
$ Arduino_Create_Agent -v
flag provided but not defined: -v
Usage of …
```
> Correct message re: enabling logging

- home.html
Fix regression introduced by #862 .
We send JSON with the default json Marshal of golang which escapes HTML elements by default. This implies that some text with`<, >, &, U+2028 and U+2029 ` char will not be converted back to their original char.
> Fix regression showing escaped charaters

- .github/workflows/check-go-dependencies-task.yml
- .github/workflows/check-go-task.yml
- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
- go.mod
- go.sum
bump version of GO
Currently go-paths-helper needs GO version >= 1.21
when running `go mod tidy`:
`go: github.com/arduino/go-paths-helper@v1.10.1 requires go@1.21, but 1.20 is requested`
Use GO version 1.21
no
> Bump GO to version 1.21

- tools/download.go
- tools/download_test.go
- tools/testdata/test_tool_index.json
- utilities/utilities.go
enhancement/security
We use [`codeclysm/extract`](https://github.com/codeclysm/extract) in our arduino GOLang projects. This is the only one that is using a custom implementation for extracting files.
Use [`codeclysm/extract`](https://github.com/codeclysm/extract) which already include security fixes (https://github.com/codeclysm/extract/pull/14)
Nop
> Use `codeclysm/extract` and remove custom implementation

- main.go
Bug fix
The agent (after #873) is no longer able to pick user defined origins in the `config.ini` file.
Restored behavior
No
> Fix origins present in `config.ini` being ignored

- README.md
The paragraph regarding the Apple silicon support has been rewritten and improved. Clarifying that all processors are supported, not only M1 ones.
> Improve the README section about Apple silicon support

- .github/workflows/release.yml
CI enhancements
The bucket we use to upload the `agent-version.json` file needed for the autoupdate will be dismissed.
We are moving `agent-version.json` to the downloads servers.
I took the chance of performing some extra activities:
- Bump installbuilder and gon
- Drop old path where we push autoupdate files (not used anymore)
> `agent-version.json` is pushed on downloads bucket now, and minor enhancements

- tools/download.go
**Arduino Create Agent** performs installation and updates of the tool dependencies required for direct communication between the local machine and the target board.
It might be necessary to execute some sort of installation process in addition to placing the files from the tool archive on the user's hard drive. This capability is provided by a "post-install script" system. If a post-install script file (`post_install.bat` on Windows, `post_install.sh` other host operating systems) is found in the tool installation, **Arduino Create Agent** automatically executes it as part of the tool installation operation.
One of the tool dependencies is `arduino:windows-drivers`, which provides the Windows device drivers for the official Arduino boards. This tool contains a post-install script that …
> Fix failure to execute tool post-install script on Windows

- upload/upload.go
- upload/upload_test.go
fix regression
After #878 the agent is no longer able to run the firmware uploader tool since it used an hack to expand FQBN and port:
```
{
"board": "arduino:renesas_uno:unor4wifi",
"port": "/dev/cu.usbmodemDC5475C5557C2",
"commandline": "\"{runtime.tools.arduino-fwuploader.path}/arduino-fwuploader\" firmware flash {network.password} -v --retries 5",
"signature": "...",
"filename": "UpdateFirmware.bin",
"extra": {
"auth": {
"password": "-a /dev/cu.usbmodemDC5475C5557C2 -b \"arduino:renesas_uno:unor4wifi\""
}
},
"hex": ""
}
```
`extra.auth.password` was removed in #878 because it was linked to network upload.
* **What is the new …
> Allow the user to specify `{fqbn}` parameter in the commandline

- .github/workflows/release.yml
~~- [ ] Tests for the changes have been added (for bug fixes / features)~~
Infra change
We currently use statically generated credentials to access to s3 buckets.
OpenID Connect allows workflows to exchange short-lived tokens directly from your cloud provider (see [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect))
Nop
> [skip-changelog] use OIDC to retrieve the credentials

- main.go
Moving the initialization of the Index after reading the .ini config.
Currently changing the `indexURL` config has no effect because the assignment of that value is performed before reading the ini file.
We now read all the configs first and then assign the `indexURL` value.
no
Tested on linux
> move Index init after reading the ini config

- main.go
**What kind of change does this PR introduce?**
The list of the accepted CORS has been modified in the following way:
- removed `register.arduino.cc`
- added `board-registration.arduino.cc`
- added a new wildcard item, to cover all the following fourth-level domains: `*.app.arduino.cc`
**What is the new behavior?**
No changes.
**Does this PR introduce a breaking change?**
No.
> Add new items to the accepted CORS and remove `register.arduino.cc`

- systray/systray_real.go
Close #928 
See #928, this will probably be part of a major rebranding
No
> change label and url in the tray icon menu

- index/index_test.go
- main_test.go
- tools/tools.go
- v2/pkgs/tools_test.go
followup of b350f563ff253d05199dda8e07718518a6cef30d
Tests used the `package_staging_index.json`
Tests are now using the `package_index.json`
no
> [skip-changelog] move tests using staging index to production one

- main.go
- serial.go
- serialport.go
Refactoring, it should not affect functionality
No changes
No
> Removed unnecessary use of channels

- serial.go
- serialport.go
Restore functionality of 'is_open' field in portlist
is_open is always false
is_open is true while the port is open for monitoring
No
> Restore functionality of 'is_open' field in portlist

- conn.go
- serial.go
- serialport.go
Mostly linter fix and code movement without any behavioural change.
No change
> Another round of code clean-up

- home.html
Changes:
- Improved the CSS code and JS code
- Added the support for the "show 'list'" options as a select
- Add an additional section to show only the "list" commands, when the user selects such option
- Fixed the code detecting "list" messages, as it was missing cases where the JSON content had a "Ports" property but its value was null instead of an empty array.
Closes #943
> Improve the "Debug Console" to add functionality and fix bugs

- certificates/certificates.go
- certificates/install_darwin.go
- certificates/install_default.go
- config/config.go
- main.go
- systray/systray_real.go
- tests/test_info.py
- tests/test_v2.py
- tests/test_ws.py
- utilities/utilities.go
Infrastructure enhancement
Safari users are prompted at startup to install the HTTPS certificate and their preference is saved in the `config` file.
It is now possible to obtain the certificate informations (installed, trusted and expiration date) from the Agent menu before performing any action on the keychain.
If the installed certificate is expiring in less than one month, the Agent will ask the user to update it.
No
> Manage the HTTPS certificate from the menu and ask Safari users to install it at startup

- certificates/certificates.go
- systray/systray_real.go
Enhancement
A message with infos on the certificate is shown to the user after a successful installation.
No
> Show message to the user after a successful certificate installation

- README.md
Update a wrong link (https://github.com/arduino/arduino-create-agent/wiki/Development), so that we can remove the wrong page in the Wiki.
> Update README.md "Development" link

- .github/workflows/release.yml
Imperfection fix
On the self-hosted runner, files are not deleted automatically and the end of each workflow run. It is necessary to introduce a step that performs the cleanup. It might be replaced in the future with a [post-job script](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/running-scripts-before-or-after-a-job).
No
> Add step to delete the signed exe on the self-hosted runner

- tools/download.go
- tools/download_test.go
- tools/tools.go
- v2/http.go
- v2/pkgs/tools.go
- v2/pkgs/tools_test.go
Code enhancement
There are two ways of dowloading tools: [Download](https://github.com/arduino/arduino-create-agent/blob/b350f563ff253d05199dda8e07718518a6cef30d/tools/download.go#L56-L177) and [Install](https://github.com/arduino/arduino-create-agent/blob/b350f563ff253d05199dda8e07718518a6cef30d/v2/pkgs/tools.go#L146-L234). The first one downloads and installs the tools from the package index only, while it is possible to provide a signed URL and a checksum to the second one to download a tool from there.
`Download` is wrapped inside `DownloadFromURL` to align it to `Install`.
- **Does this PR …
> Check if a signed URL is specified and use it download tools

- main_test.go
- tools/download_test.go
- tools/testdata/test_tool_index.json
- v2/pkgs/pkgs.go
- v2/pkgs/testdata/test_tool_index.json
- v2/pkgs/tools.go
- v2/pkgs/tools_test.go
bug fix
The agent is not able to intall `esptool` after 1.6.0 (more details in #980)
The old behavior is restored
No
> Fix agent not able to install `esptool` after 1.6.0

- v2/pkgs/tools.go
Code enhancement
Insert lock while reading from the installed map to prevent concurrent access.
No
> Insert lock while reading from the installed map

- .github/workflows/check-go-dependencies-task.yml
A breaking change was made in the 3.2.1 release of the [**actions/upload-artifact**](https://github.com/actions/upload-artifact) action (https://github.com/actions/upload-artifact/issues/602), without doing a major version bump as would be done in a responsibly maintained project. The action now defaults to not uploading "hidden" files.
This project's "**Check Go Dependencies**" workflow uses the [**Licensed**](https://github.com/github/licensed) tool to check for incompatible dependency licenses. The dependencies license metadata cache used by **Licensed** is stored in a folder named `.licensed`.
In order to facilitate updates, the workflow uploads the generated dependencies license metadata cache as a [workflow artifact](https://docs.github.com/actions/writing-workflows/choosing-what-you …
> [skip-changelog] Configure actions/upload-artifact action to upload required hidden files

- conn.go
- main_test.go
When we send an HTTP request to the `upload` endpoint, we include a JSON payload. This payload is then decoded into the `Upload` struct using the `BindJSON` function from the Gin framework.
However, when we have a `[]byte` field, the expectation is that the corresponding field sent over the wire is base64 encoded with padding. If the value is not properly padded, the function returns an error.
Before this PR, we were silently ignoring this error, leading to odd behavior on the frontend:
- A payload with a `hex` field containing an unpadded base64 string is sent.
- `BindJSON` silently fails and sets the HTTP status to 400.
- Despite this failure, we continue executing the handler.
- Once the handler completes, we return the 400 error, but by that point, the upload process has already …
> upload: don't ignore BindJSON errors

- README.md
Change the README with the correct link to the Cloud editor.
> docs: update references from Arduino Create Web Editor to Arduino Cloud 

- .github/workflows/check-go-task.yml
The `check-errors` was failing with this error:
```
Reading state information...
E: Unable to locate package libwebkit2gtk-4.0-dev
E: Couldn't find any package by glob 'libwebkit2gtk-4.0-dev'
```
This may be due to the fact the ubuntu:latest is using ubuntu24.0 starting from 5th Dec 2024. https://github.com/actions/runner-images/issues/10636
Use the `libwebkit2gtk-4.1-0` instead of `libwebkit2gtk-4.0-dev`
> ci: fix the `check-errors` by updating `libwebkit2gtk`

- .github/workflows/publish-go-tester-task.yml
There are two "Build the Agent for macos amd 64" name in the github action.
Rename the second with the `arm`.
> fix(ci): change the name of macos build for `arm` platform

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
The github actions fails because the macos-12 runner is [deprecated](https://github.com/actions/runner-images/issues/10721)
Bump to macos-13
> ci: update macOS version in publish workflow to macos-13

- .github/workflows/check-go-dependencies-task.yml
This GitHub Actions action is used by the "Check Go Dependencies" workflow to install the "Licensed" tool in the runner workspace. At the time the workflow was developed, the action was owned by GitHub user `jonabc`, and so the action was referenced as `jonabc/setup-licensed` in the workflow.
Since that time, the action was transferred to the `github` GitHub organization:
https://github.com/github/setup-licensed
Making things more confusing is the fact that there is now [a development fork](https://github.com/jonabc/setup-licensed) of the `github/setup-licensed` repository under GitHub user `jonabc`'s account, meaning that the redirect GitHub provides from the old to the new repository after a transfer does not exist for this action. This resulted in the workflow referencing an outdated …
> Correct "setup-licensed" action ref in dependencies license check workflow

- .github/workflows/check-go-dependencies-task.yml
The [**Licensed**](https://github.com/licensee/licensed) tool is used to check the project's compatibility with the licensing of its dependencies.
This tool is installed by the dependency license check GitHub Actions workflow using the [**licensee/setup-licensed**](https://github.com/licensee/setup-licensed) GitHub Actions action. This action attempts the installation according to the following procedure:
1. Install [the Ruby gem](https://rubygems.org/gems/licensed).
2. If gem installation fails, install the pre-built executable from the GitHub release asset in the `licensee/licensed` repo.
Previously, the first of these installation methods was failing:
```text
/usr/bin/gem install licensed -v 3.9.1
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write …
```
> Configure dependency license check workflows to allow "Licensed" install via gem

- .licenses/arduino-create-agent/go/github.com/arduino/go-serial-utils.dep.yml
- .licenses/arduino-create-agent/go/github.com/blang/semver.dep.yml
- .licenses/arduino-create-agent/go/github.com/creack/goselect.dep.yml
- .licenses/arduino-create-agent/go/github.com/gin-contrib/sse.dep.yml
- .licenses/arduino-create-agent/go/github.com/gin-gonic/gin/binding.dep.yml
- .licenses/arduino-create-agent/go/github.com/gin-gonic/gin/internal/bytesconv.dep.yml
- .licenses/arduino-create-agent/go/github.com/gin-gonic/gin/internal/json.dep.yml
- .licenses/arduino-create-agent/go/github.com/gin-gonic/gin/render.dep.yml
- .licenses/arduino-create-agent/go/github.com/googollee/go-engine.io.dep.yml
- .licenses/arduino-create-agent/go/github.com/googollee/go-engine.io/message.dep.yml
- .licenses/arduino-create-agent/go/github.com/googollee/go-engine.io/parser.dep.yml
- .licenses/arduino-create-agent/go/github.com/googollee/go-engine.io/polling.dep.yml
- .licenses/arduino-create-agent/go/github.com/googollee/go-engine.io/transport.dep.yml
- .licenses/arduino-create-agent/go/github.com/googollee/go-engine.io/websocket.dep.yml
- .licenses/arduino-create-agent/go/github.com/h2non/filetype.dep.yml
- .licenses/arduino-create-agent/go/github.com/h2non/filetype/matchers.dep.yml
- .licenses/arduino-create-agent/go/github.com/h2non/filetype/matchers/isobmff.dep.yml
- .licenses/arduino-create-agent/go/github.com/h2non/filetype/types.dep.yml
- .licenses/arduino-create-agent/go/github.com/mattn/go-shellwords.dep.yml
- .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/internal/characters.dep.yml
- .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/internal/danger.dep.yml
- .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/internal/tracker.dep.yml
- .licenses/arduino-create-agent/go/github.com/xrash/smetrics.dep.yml
- .licenses/arduino-create-agent/go/go.bug.st/serial/unixutils.dep.yml
- .licenses/arduino-create-agent/go/golang.org/x/text/internal/language.dep.yml
- .licenses/arduino-create-agent/go/gopkg.in/inconshreveable/go-update.v0/download.dep.yml
The [**Licensed**](https://github.com/licensee/licensed) tool is used to check for incompatible licenses in the project dependencies. The tool relies on a cache of metadata stored in the repository.
An older version of **Licensed** was in use at the time the cache was established. There are some minor differences in the format of the metadata generated by the version of **Licensed** currently in use.
Even though there is no technical significance to the format differences, they are disruptive in that they result in irrelevant diffs in specific metadata files when they are regenerated after a dependency bump. Rather than dealing with these diffs over time, it will be best to instead update the metadata to the new format comprehensively.
> Update format of dependency license metadata

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release.yml
Fix issue https://github.com/arduino/arduino-create-agent/issues/1010
> chore(.github): update workflow to use ubuntu-22.04 instead of ubuntu-20.04
