arduino/arduino-create-agent

bufferflow_tinyg.go

Fix https://github.com/arduino/webide/issues/290

Remove application of newline character by trusting input from client

---

bufferflow_timed.go

Only send messages if there is something to send.
Fix issue https://github.com/arduino/webide/issues/483

Cleanup output

---

main.go

Be sure we have a comma + space separated list

---

README.md

README: add build instructions

---

compile_webidebridge.sh

The script contains some bashims like echo -e so better make it
explicit.
Signed-off-by: Riccardo Magliocchetti <riccardo.magliocchetti@gmail.com>

Make it clear that bash is required

---

main.go

Reverts arduino/arduino-create-agent#58

Revert "Stricter CORS headers"

---

main.go

Only listen to localhost by default

---

conn.go

Don't check for the signature validity for a network upload

---

programmer.go

Solves the disappearance of Use1200bpsTouch

Fix typo 1200bps

---

upload/upload.go

It should be fixed with the small delay added.

Fix upload issue with Due Programming port

---

main.go

Apparently mac crashes if the systray icon is launched in a goroutine, so we have to launch everything else in a goroutine

Make systray the main level routine

---

README.md

This commit fixes minor typos in README.md

README.md: Fixed minor typos

---

go.mod
go.sum

update sytray to latest available version

---

main.go

Close #78
#204 does not apply anymore

Log error, if certificate is not found

---

go.mod
go.sum
info.go
seriallist.go
serialport.go
upload/upload.go

update go.bug.st/serial to latest version

---

.github/workflows/release.yml

CI enhancement
The release changelog must be made manually
The changelog is generated automagically using :sparkles: [arduino/create-changelog](https://github.com/arduino/create-changelog)
no

add automatic changelog generation step

---

.github/workflows/release.yml

bump installbuilder container to the latest available version (21.6.0) https://installbuilder.com/changelog.html
This version should solve some bugs on osx
no

bump installbuilder container to the latest version

---

main.go

new origin
the agent does not work on https://cloud.arduino.cc/
THe agent works on https://cloud.arduino.cc/
no

add new origin to the agent

---

.github/workflows/release.yml

https://github.com/flickr-downloadr/ubuntu-install-builder/commit/e8350c83298baf54eedd1d48643956242e874e40
bump installbuilder to the latest available version 
no

bump installbuilder to 22.10.0

---

.github/workflows/test-go-task.yml

CI enhancement
The CI sometime fails with:
```
[2023-09-04T14:00:44.591Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
According to [this](https://github.com/codecov/codecov-action/issues/557#issuecomment-1224970469), it should remove the problem 
- **Does this PR introduce a breaking …

[skip-changelog] Add Codecov token

---

.github/workflows/release.yml

infra bump
We use 22.10.0 version of installbuilder
Include https://github.com/flickr-downloadr/ubuntu-install-builder/commit/7114edc308f61042aa7f6aad4836005d08518894
Changelog [here](https://installbuilder.com/changelog)
nop

Bump Installbuilder to 23.7.0

---

home.html

See: https://arduino.atlassian.net/browse/PNX-354

[PNX-354] input sanitization

---

.github/workflows/release.yml

Followup of #901 
I forgot some cosmetic parameters
The CI works
No

[skip-changelog] fix release CI

---

main.go

`register.arduino.cc` has been added to the accepted origins.
No changes in the behavior.
No

Add `register.arduino.cc` to the accepted extra origins

---

README.md

Fix spelling
Misspelled, inconsistent on the same line
Spelled correctly, consistent
No

Fix spelling of the word "development" in README.md.
